export const PAYMENT_PROCESS_REQUEST = 'PAYMENT_PROCESS_REQUEST';
export const PAYMENT_PROCESS_SUCCESS = 'PAYMENT_PROCESS_SUCCESS';
export const PAYMENT_PROCESS_FAIL = 'PAYMENT_PROCESS_FAIL';

export const PAYMENT_INTENT_REQUEST = 'PAYMENT_INTENT_REQUEST';
export const PAYMENT_INTENT_SUCCESS = 'PAYMENT_INTENT_SUCCESS';
export const PAYMENT_INTENT_FAIL = 'PAYMENT_INTENT_FAIL';
